'use strict';

/**
 * Demo catalog for a construction materials market.
 * Prices are illustrative (UZS). Suppliers, phone numbers and Telegram
 * handles are fictional.
 */

const L = (uz, ru) => ({ uz, ru });
const spec = (labelUz, labelRu, valueUz, valueRu = valueUz) => ({ label: L(labelUz, labelRu), value: L(valueUz, valueRu) });
const img = (name) => [`/img/catalog/${name}.svg`];

const categories = [
  {
    slug: 'cement-mixes',
    icon: 'cement',
    sortOrder: 10,
    name: L('Sement va quruq aralashmalar', 'Цемент и сухие смеси'),
    description: L(
      'Portlandsement, shtukaturka, plitka yelimi, nivelir aralashmalari va inert materiallar.',
      'Портландцемент, штукатурки, плиточный клей, наливные полы и сыпучие материалы.'
    )
  },
  {
    slug: 'blocks-bricks',
    icon: 'blocks',
    sortOrder: 20,
    name: L('Bloklar va gʻisht', 'Блоки и кирпич'),
    description: L('Gazobeton, keramik va yuzaki gʻisht, keramzitobeton bloklar.', 'Газобетон, керамический и облицовочный кирпич, керамзитоблоки.')
  },
  {
    slug: 'lumber',
    icon: 'lumber',
    sortOrder: 30,
    name: L('Yogʻoch materiallari', 'Пиломатериалы'),
    description: L('Qirrali taxta, brus, fanera va OSB plitalar.', 'Обрезная доска, брус, фанера и плиты OSB.')
  },
  {
    slug: 'drywall',
    icon: 'drywall',
    sortOrder: 40,
    name: L('Gipsokarton va profillar', 'Гипсокартон и профили'),
    description: L('GKL listlar, metall profillar va karkas uchun komplektlovchilar.', 'Листы ГКЛ, металлические профили и комплектующие для каркаса.')
  },
  {
    slug: 'pipes-fittings',
    icon: 'pipes',
    sortOrder: 50,
    name: L('Quvurlar va fitinglar', 'Трубы и фитинги'),
    description: L(
      'Suv taʼminoti, isitish va kanalizatsiya uchun PPR va PVX quvurlar.',
      'Трубы PPR и ПВХ для водоснабжения, отопления и канализации.'
    )
  },
  {
    slug: 'fasteners',
    icon: 'fasteners',
    sortOrder: 60,
    name: L('Mahkamlash vositalari', 'Крепёж'),
    description: L('Shuruplar, ankerlar, boltlar, dyubellar va mixlar.', 'Саморезы, анкеры, болты, дюбели и гвозди.')
  },
  {
    slug: 'rebar-metal',
    icon: 'rebar',
    sortOrder: 70,
    name: L('Armatura va metall prokat', 'Арматура и металлопрокат'),
    description: L('Armatura, tosh devor toʻrlari va profil quvurlar.', 'Арматура, кладочные сетки и профильные трубы.')
  },
  {
    slug: 'power-tools',
    icon: 'tools',
    sortOrder: 80,
    name: L('Elektr asboblar', 'Электроинструмент'),
    description: L(
      'Perforatorlar, burchak silliqlash mashinalari va shurupovyortlar.',
      'Перфораторы, угловые шлифмашины и шуруповёрты.'
    )
  },
  {
    slug: 'roofing-insulation',
    icon: 'roofing',
    sortOrder: 90,
    name: L('Tom va izolyatsiya', 'Кровля и изоляция'),
    description: L('Profnastil, mineral paxta, penopolistirol va gidroizolyatsiya.', 'Профнастил, минвата, пенополистирол и гидроизоляция.')
  },
  {
    slug: 'paints-finishes',
    icon: 'paint',
    sortOrder: 100,
    name: L('Boʻyoqlar va pardozlash', 'Краски и отделка'),
    description: L('Ichki va fasad boʻyoqlari, gruntovkalar.', 'Интерьерные и фасадные краски, грунтовки.')
  }
];

const brands = [
  { slug: 'bb-pro', name: 'BB Pro', country: 'UZ' },
  { slug: 'knauf', name: 'Knauf', country: 'DE' },
  { slug: 'ceresit', name: 'Ceresit', country: 'DE' },
  { slug: 'bonolit', name: 'Bonolit', country: 'RU' },
  { slug: 'wienerberger', name: 'Wienerberger', country: 'AT' },
  { slug: 'kronospan', name: 'Kronospan', country: 'AT' },
  { slug: 'kalde', name: 'Kalde', country: 'TR' },
  { slug: 'wavin', name: 'Wavin', country: 'NL' },
  { slug: 'fischer', name: 'Fischer', country: 'DE' },
  { slug: 'bosch', name: 'Bosch', country: 'DE' },
  { slug: 'makita', name: 'Makita', country: 'JP' },
  { slug: 'dewalt', name: 'DeWalt', country: 'US' },
  { slug: 'grand-line', name: 'Grand Line', country: 'RU' },
  { slug: 'rockwool', name: 'Rockwool', country: 'DK' },
  { slug: 'technonicol', name: 'TechnoNICOL', country: 'RU' },
  { slug: 'tikkurila', name: 'Tikkurila', country: 'FI' }
];

const suppliers = [
  {
    slug: 'sement-markaz',
    name: 'Sement Markaz',
    stallNumber: 'A-12',
    phone: '+998990000112',
    telegram: 'sement_markaz_demo',
    whatsapp: '+998990000112',
    workingHours: '07:30–18:00',
    workingDays: 'mon_sat',
    deliveryAvailable: true,
    paymentMethods: ['cash', 'transfer'],
    isVerified: true,
    isFeatured: true,
    description: L(
      'Sement, quruq aralashmalar va inert materiallar ulgurji savdosi. Obyektga manipulyator bilan yetkazib beramiz.',
      'Оптовая продажа цемента, сухих смесей и сыпучих материалов. Доставка на объект манипулятором.'
    ),
    address: L('A qator, 12-doʻkon', 'Ряд A, павильон 12'),
    deliveryNote: L('Toshkent boʻylab 5 tonnadan bepul', 'Бесплатно по Ташкенту от 5 тонн')
  },
  {
    slug: 'blok-servis',
    name: 'Blok Servis',
    stallNumber: 'A-27',
    phone: '+998990000127',
    telegram: 'blok_servis_demo',
    workingHours: '08:00–18:00',
    workingDays: 'mon_sat',
    deliveryAvailable: true,
    paymentMethods: ['cash', 'card', 'transfer'],
    isVerified: true,
    isFeatured: true,
    description: L(
      'Gazobeton, gʻisht va keramzitobeton bloklar poddonlarda. Hajm boʻyicha maslahat beramiz.',
      'Газобетон, кирпич и керамзитоблоки на поддонах. Поможем рассчитать объём.'
    ),
    address: L('A qator, 27-doʻkon', 'Ряд A, павильон 27'),
    deliveryNote: L('Poddonlar qaytariladi', 'Поддоны возвратные')
  },
  {
    slug: 'yogoch-ustasi',
    name: 'Yogʻoch Ustasi',
    stallNumber: 'B-04',
    phone: '+998990000204',
    telegram: 'yogoch_ustasi_demo',
    workingHours: '08:00–17:30',
    workingDays: 'mon_sat',
    deliveryAvailable: true,
    paymentMethods: ['cash', 'transfer'],
    isVerified: true,
    isFeatured: true,
    description: L(
      'Qaragʻay va archa yogʻoch materiallari, fanera va OSB. Oʻlcham boʻyicha kesib beramiz.',
      'Пиломатериалы из сосны и ели, фанера и OSB. Распил в размер.'
    ),
    address: L('B qator, 4-doʻkon', 'Ряд B, павильон 4'),
    deliveryNote: L('Uzun yuklar uchun alohida transport', 'Отдельный транспорт для длинномеров')
  },
  {
    slug: 'gips-pro',
    name: 'Gips Pro',
    stallNumber: 'B-18',
    phone: '+998990000218',
    telegram: 'gips_pro_demo',
    workingHours: '08:00–18:00',
    workingDays: 'mon_sat',
    deliveryAvailable: false,
    paymentMethods: ['cash', 'card'],
    isVerified: true,
    isFeatured: false,
    description: L('Gipsokarton tizimlari va shtukaturka aralashmalari.', 'Системы гипсокартона и штукатурные смеси.'),
    address: L('B qator, 18-doʻkon', 'Ряд B, павильон 18')
  },
  {
    slug: 'aqua-quvur',
    name: 'Aqua Quvur',
    stallNumber: 'C-21',
    phone: '+998990000321',
    telegram: 'aqua_quvur_demo',
    whatsapp: '+998990000321',
    workingHours: '09:00–18:00',
    workingDays: 'daily',
    deliveryAvailable: false,
    paymentMethods: ['cash', 'card'],
    isVerified: true,
    isFeatured: true,
    description: L('Suv taʼminoti, isitish va kanalizatsiya uchun quvurlar va fitinglar.', 'Трубы и фитинги для водоснабжения, отопления и канализации.'),
    address: L('C qator, 21-doʻkon', 'Ряд C, павильон 21')
  },
  {
    slug: 'krepyoj-market',
    name: 'Krepyoj Market',
    stallNumber: 'C-35',
    phone: '+998990000335',
    telegram: 'krepyoj_market_demo',
    workingHours: '08:30–18:00',
    workingDays: 'mon_sat',
    deliveryAvailable: false,
    paymentMethods: ['cash'],
    isVerified: false,
    isFeatured: false,
    description: L('Mahkamlash vositalarining 3000 dan ortiq turi, dona va quti boʻyicha.', 'Более 3000 позиций крепежа поштучно и коробками.'),
    address: L('C qator, 35-doʻkon', 'Ряд C, павильон 35')
  },
  {
    slug: 'metall-invest',
    name: 'Metall Invest',
    stallNumber: 'D-07',
    phone: '+998990000407',
    telegram: 'metall_invest_demo',
    workingHours: '08:00–18:00',
    workingDays: 'mon_sat',
    deliveryAvailable: true,
    paymentMethods: ['cash', 'transfer'],
    isVerified: true,
    isFeatured: true,
    description: L('Armatura va metall prokat, oʻlcham boʻyicha kesish va bukish.', 'Арматура и металлопрокат, резка и гибка в размер.'),
    address: L('D qator, 7-doʻkon', 'Ряд D, павильон 7'),
    deliveryNote: L('Kran-manipulyator bilan yetkazish', 'Доставка краном-манипулятором')
  },
  {
    slug: 'asbob-pro',
    name: 'Asbob Pro',
    stallNumber: 'E-15',
    phone: '+998990000515',
    telegram: 'asbob_pro_demo',
    workingHours: '09:00–19:00',
    workingDays: 'daily',
    deliveryAvailable: true,
    paymentMethods: ['cash', 'card', 'transfer'],
    isVerified: true,
    isFeatured: true,
    description: L('Professional elektr asboblar, rasmiy kafolat va servis.', 'Профессиональный электроинструмент, официальная гарантия и сервис.'),
    address: L('E qator, 15-doʻkon', 'Ряд E, павильон 15'),
    deliveryNote: L('Toshkent boʻylab kuryer', 'Курьер по Ташкенту')
  },
  {
    slug: 'tom-master',
    name: 'Tom Master',
    stallNumber: 'F-03',
    phone: '+998990000603',
    telegram: 'tom_master_demo',
    workingHours: '08:00–18:00',
    workingDays: 'mon_sat',
    deliveryAvailable: true,
    paymentMethods: ['cash', 'transfer'],
    isVerified: false,
    isFeatured: false,
    description: L('Tom yopish materiallari, issiqlik va gidroizolyatsiya.', 'Кровельные материалы, тепло- и гидроизоляция.'),
    address: L('F qator, 3-doʻkon', 'Ряд F, павильон 3')
  },
  {
    slug: 'rang-uy',
    name: 'Rang Uy',
    stallNumber: 'F-11',
    phone: '+998990000611',
    telegram: 'rang_uy_demo',
    workingHours: '09:00–18:00',
    workingDays: 'mon_sat',
    deliveryAvailable: false,
    paymentMethods: ['cash', 'card'],
    isVerified: true,
    isFeatured: false,
    description: L('Boʻyoqlar, gruntovkalar va rang tanlash xizmati.', 'Краски, грунтовки и колеровка.'),
    address: L('F qator, 11-doʻkon', 'Ряд F, павильон 11')
  }
];

const MPA = (v) => spec('Siqilishdagi mustahkamlik', 'Прочность на сжатие', `${v} MPa`, `${v} МПа`);

const products = [
  /* ------------------------------------------------ cement & mixes */
  {
    sku: 'CEM-M500-50',
    category: 'cement-mixes',
    brand: 'bb-pro',
    supplier: 'sement-markaz',
    name: L('Portlandsement M500 D0, 50 kg', 'Портландцемент М500 Д0, 50 кг'),
    description: L(
      'Qoʻshimchalarsiz yuqori markali portlandsement. Poydevor, monolit karkas va temir-beton buyumlar uchun mos. Sovuq va namlikka chidamli beton olish imkonini beradi.',
      'Высокомарочный портландцемент без минеральных добавок. Подходит для фундаментов, монолитного каркаса и ЖБИ. Позволяет получать морозо- и влагостойкий бетон.'
    ),
    materialType: 'cement',
    grade: 'M500 D0',
    unit: 'bag',
    price: 72000,
    priceTiers: [{ minQty: 50, price: 69000 }, { minQty: 200, price: 66500 }],
    unitsPerPallet: 40,
    weightKg: 50,
    specs: [
      MPA(50),
      spec('Qotish boshlanishi', 'Начало схватывания', '≥ 45 daqiqa', '≥ 45 минут'),
      spec('Standart', 'Стандарт', 'GOST 31108-2016')
    ],
    stock: { status: 'in_stock', quantity: 1200 },
    images: img('cement-bag'),
    isFeatured: true
  },
  {
    sku: 'CEM-M400-50',
    category: 'cement-mixes',
    brand: 'bb-pro',
    supplier: 'sement-markaz',
    name: L('Portlandsement M400 D20, 50 kg', 'Портландцемент М400 Д20, 50 кг'),
    description: L(
      'Umumiy qurilish ishlari uchun sement: gʻisht terish, styajka, shtukaturka va M300 gacha beton.',
      'Цемент для общестроительных работ: кладка, стяжка, штукатурка и бетон до М300.'
    ),
    materialType: 'cement',
    grade: 'M400 D20',
    unit: 'bag',
    price: 64000,
    priceTiers: [{ minQty: 50, price: 61500 }, { minQty: 200, price: 59000 }],
    unitsPerPallet: 40,
    weightKg: 50,
    specs: [MPA(40), spec('Mineral qoʻshimchalar', 'Минеральные добавки', 'gacha 20%', 'до 20%')],
    stock: { status: 'in_stock', quantity: 2400 },
    images: img('cement-bag-gray')
  },
  {
    sku: 'CEM-TA-CM11',
    category: 'cement-mixes',
    brand: 'ceresit',
    supplier: 'sement-markaz',
    name: L('Plitka yelimi Ceresit CM 11, 25 kg', 'Плиточный клей Ceresit CM 11, 25 кг'),
    description: L(
      'Keramik plitkalarni ichki va tashqi ishlarda yopishtirish uchun sement asosidagi yelim.',
      'Клей на цементной основе для укладки керамической плитки внутри и снаружи помещений.'
    ),
    materialType: 'cement',
    grade: 'C1 T',
    unit: 'bag',
    price: 78000,
    priceTiers: [{ minQty: 40, price: 74000 }],
    unitsPerPallet: 48,
    weightKg: 25,
    specs: [
      spec('Sarfi', 'Расход', '1,5–4 kg/m²', '1,5–4 кг/м²'),
      spec('Ochiq vaqt', 'Открытое время', '15 daqiqa', '15 минут'),
      spec('Ish harorati', 'Температура работ', '+5…+30 °C')
    ],
    stock: { status: 'in_stock', quantity: 380 },
    images: img('mix-bag-yellow')
  },
  {
    sku: 'CEM-GP-ROTBAND',
    category: 'cement-mixes',
    brand: 'knauf',
    supplier: 'gips-pro',
    name: L('Gipsli shtukaturka Knauf Rotband, 30 kg', 'Штукатурка гипсовая Knauf Rotband, 30 кг'),
    description: L(
      'Devor va shiftlarni qoʻlda suvash uchun universal gipsli aralashma. Silliq va yoriqsiz sirt beradi.',
      'Универсальная гипсовая смесь для ручного оштукатуривания стен и потолков. Даёт гладкую поверхность без трещин.'
    ),
    materialType: 'gypsum',
    grade: '',
    unit: 'bag',
    price: 89000,
    priceTiers: [{ minQty: 35, price: 85000 }],
    unitsPerPallet: 35,
    weightKg: 30,
    specs: [
      spec('Qatlam qalinligi', 'Толщина слоя', '5–50 mm', '5–50 мм'),
      spec('Sarfi (10 mm)', 'Расход (10 мм)', '8,5 kg/m²', '8,5 кг/м²')
    ],
    stock: { status: 'low_stock', quantity: 60 },
    images: img('mix-bag-blue'),
    isFeatured: true
  },
  {
    sku: 'CEM-SL-CN175',
    category: 'cement-mixes',
    brand: 'ceresit',
    supplier: 'sement-markaz',
    name: L('Oʻzi tekislanuvchi pol Ceresit CN 175, 25 kg', 'Наливной пол Ceresit CN 175, 25 кг'),
    description: L(
      'Tez qotuvchi nivelir aralashmasi. 1 mm dan 10 mm gacha qatlam, 6 soatdan keyin yurish mumkin.',
      'Быстротвердеющая самовыравнивающаяся смесь. Слой от 1 до 10 мм, можно ходить через 6 часов.'
    ),
    materialType: 'cement',
    grade: 'CT-C20-F5',
    unit: 'bag',
    price: 118000,
    weightKg: 25,
    specs: [spec('Qatlam qalinligi', 'Толщина слоя', '1–10 mm', '1–10 мм'), spec('Yurish mumkin', 'Хождение через', '6 soatdan keyin', 'через 6 часов')],
    stock: { status: 'on_order', quantity: null },
    leadTimeDays: 3,
    images: img('mix-bag-teal')
  },
  {
    sku: 'CEM-SAND-W',
    category: 'cement-mixes',
    brand: null,
    supplier: 'sement-markaz',
    name: L('Yuvilgan qurilish qumi', 'Песок строительный мытый'),
    description: L(
      'Beton va qorishmalar uchun fraksiyalangan yuvilgan qum. Samosval bilan tonna hisobida yetkaziladi.',
      'Фракционированный мытый песок для бетона и растворов. Поставка самосвалом, цена за тонну.'
    ),
    materialType: 'other',
    grade: 'Mk 2,0–2,5',
    unit: 'ton',
    price: 160000,
    priceTiers: [{ minQty: 20, price: 145000 }],
    minOrderQty: 5,
    orderStep: 0.5,
    specs: [spec('Yiriklik moduli', 'Модуль крупности', '2,0–2,5'), spec('Changli zarralar', 'Пылевидные частицы', '≤ 1%')],
    stock: { status: 'in_stock', quantity: null },
    leadTimeDays: 1,
    images: img('sand-heap')
  },

  /* ------------------------------------------------ blocks & bricks */
  {
    sku: 'BLK-D500-600',
    category: 'blocks-bricks',
    brand: 'bonolit',
    supplier: 'blok-servis',
    name: L('Gazobeton blok D500, 600×300×200 mm', 'Газобетонный блок D500, 600×300×200 мм'),
    description: L(
      'Tashqi va ichki yuk koʻtaruvchi devorlar uchun avtoklavli gazobeton. Yelimga teriladi, issiqlikni yaxshi saqlaydi.',
      'Автоклавный газобетон для наружных и несущих стен. Кладка на клей, отлично сохраняет тепло.'
    ),
    materialType: 'aerated_concrete',
    grade: 'D500 B2.5',
    unit: 'm3',
    price: 860000,
    priceTiers: [{ minQty: 10, price: 830000 }, { minQty: 30, price: 805000 }],
    minOrderQty: 0.9,
    orderStep: 0.1,
    unitsPerPallet: 1.8,
    dimensions: { lengthMm: 600, widthMm: 300, heightMm: 200 },
    weightKg: 500,
    specs: [
      spec('Mustahkamlik sinfi', 'Класс прочности', 'B2.5'),
      spec('Issiqlik oʻtkazuvchanlik', 'Теплопроводность', '0,12 Vt/(m·°C)', '0,12 Вт/(м·°С)'),
      spec('Sovuqbardoshlik', 'Морозостойкость', 'F100'),
      spec('1 m³ dagi bloklar', 'Блоков в 1 м³', '27,7 dona', '27,7 шт.')
    ],
    stock: { status: 'in_stock', quantity: 340 },
    images: img('aac-block'),
    isFeatured: true
  },
  {
    sku: 'BLK-D500-100',
    category: 'blocks-bricks',
    brand: 'bonolit',
    supplier: 'blok-servis',
    name: L('Gazobeton peregorodka bloki D500, 600×250×100 mm', 'Газобетонный перегородочный блок D500, 600×250×100 мм'),
    description: L('Ichki toʻsiqlar uchun yupqa gazobeton blok.', 'Тонкий газобетонный блок для межкомнатных перегородок.'),
    materialType: 'aerated_concrete',
    grade: 'D500 B2.5',
    unit: 'piece',
    price: 16500,
    priceTiers: [{ minQty: 200, price: 15800 }, { minQty: 1000, price: 15000 }],
    minOrderQty: 10,
    unitsPerPallet: 120,
    dimensions: { lengthMm: 600, widthMm: 100, heightMm: 250 },
    weightKg: 9,
    stock: { status: 'in_stock', quantity: 5400 },
    images: img('aac-block-thin')
  },
  {
    sku: 'BLK-BRK-M150',
    category: 'blocks-bricks',
    brand: 'bb-pro',
    supplier: 'blok-servis',
    name: L('Keramik gʻisht M150, toʻliq, 250×120×65 mm', 'Кирпич керамический полнотелый М150, 250×120×65 мм'),
    description: L(
      'Yuk koʻtaruvchi devorlar, ustunlar va poydevorlar uchun pishiq qizil gʻisht.',
      'Красный полнотелый кирпич для несущих стен, столбов и фундаментов.'
    ),
    materialType: 'ceramic',
    grade: 'M150',
    unit: 'piece',
    price: 1650,
    priceTiers: [{ minQty: 1000, price: 1550 }, { minQty: 5000, price: 1450 }],
    minOrderQty: 100,
    orderStep: 50,
    unitsPerPallet: 400,
    dimensions: { lengthMm: 250, widthMm: 120, heightMm: 65 },
    weightKg: 3.6,
    specs: [spec('Sovuqbardoshlik', 'Морозостойкость', 'F50'), spec('Suv shimish', 'Водопоглощение', '≤ 12%')],
    stock: { status: 'in_stock', quantity: 48000 },
    images: img('brick-red'),
    isFeatured: true
  },
  {
    sku: 'BLK-BRK-FACE',
    category: 'blocks-bricks',
    brand: 'wienerberger',
    supplier: 'blok-servis',
    name: L('Yuzaki gʻisht M175, 250×120×88 mm', 'Кирпич облицовочный М175, 250×120×88 мм'),
    description: L('Fasadlar uchun bir tekis rangli, aniq geometriyali gʻisht.', 'Облицовочный кирпич ровного цвета и точной геометрии для фасадов.'),
    materialType: 'ceramic',
    grade: 'M175',
    unit: 'piece',
    price: 3900,
    priceTiers: [{ minQty: 1000, price: 3700 }],
    minOrderQty: 50,
    orderStep: 50,
    unitsPerPallet: 352,
    dimensions: { lengthMm: 250, widthMm: 120, heightMm: 88 },
    weightKg: 2.9,
    stock: { status: 'low_stock', quantity: 900 },
    images: img('brick-face')
  },
  {
    sku: 'BLK-CIN-390',
    category: 'blocks-bricks',
    brand: null,
    supplier: 'blok-servis',
    name: L('Keramzitobeton blok, 390×190×188 mm', 'Керамзитобетонный блок, 390×190×188 мм'),
    description: L('Kovak devor bloki: tez terish va yengil devor.', 'Пустотелый стеновой блок: быстрая кладка и лёгкая стена.'),
    materialType: 'concrete',
    grade: 'M75',
    unit: 'piece',
    price: 7200,
    priceTiers: [{ minQty: 500, price: 6800 }],
    minOrderQty: 20,
    unitsPerPallet: 72,
    dimensions: { lengthMm: 390, widthMm: 190, heightMm: 188 },
    weightKg: 13,
    stock: { status: 'in_stock', quantity: 3100 },
    images: img('cinder-block')
  },

  /* ------------------------------------------------ lumber */
  {
    sku: 'WOD-BRD-50150',
    category: 'lumber',
    brand: null,
    supplier: 'yogoch-ustasi',
    name: L('Qirrali taxta 50×150×6000 mm, qaragʻay', 'Доска обрезная 50×150×6000 мм, сосна'),
    description: L(
      'Tom konstruksiyalari, yopmalar va qolip uchun 1-navli quritilgan taxta.',
      'Сухая доска первого сорта для стропильных систем, перекрытий и опалубки.'
    ),
    materialType: 'wood',
    grade: 'I',
    unit: 'm3',
    price: 4200000,
    priceTiers: [{ minQty: 5, price: 4050000 }, { minQty: 15, price: 3900000 }],
    minOrderQty: 0.5,
    orderStep: 0.1,
    dimensions: { lengthMm: 6000, widthMm: 150, thicknessMm: 50 },
    weightKg: 520,
    specs: [
      spec('Namligi', 'Влажность', '18–22%'),
      spec('Yogʻoch turi', 'Порода', 'Qaragʻay', 'Сосна'),
      spec('1 m³ dagi soni', 'Штук в 1 м³', '22 dona', '22 шт.')
    ],
    stock: { status: 'in_stock', quantity: 64 },
    images: img('boards'),
    isFeatured: true
  },
  {
    sku: 'WOD-BEAM-100',
    category: 'lumber',
    brand: null,
    supplier: 'yogoch-ustasi',
    name: L('Brus 100×100×6000 mm, qaragʻay', 'Брус 100×100×6000 мм, сосна'),
    description: L('Karkas, tom va yogʻoch yopmalar uchun brus.', 'Брус для каркаса, стропил и деревянных перекрытий.'),
    materialType: 'wood',
    grade: 'I',
    unit: 'm3',
    price: 4400000,
    priceTiers: [{ minQty: 5, price: 4250000 }],
    minOrderQty: 0.5,
    orderStep: 0.1,
    dimensions: { lengthMm: 6000, widthMm: 100, thicknessMm: 100 },
    weightKg: 520,
    specs: [spec('1 m³ dagi soni', 'Штук в 1 м³', '16,6 dona', '16,6 шт.')],
    stock: { status: 'in_stock', quantity: 28 },
    images: img('beam')
  },
  {
    sku: 'WOD-BRD-25100',
    category: 'lumber',
    brand: null,
    supplier: 'yogoch-ustasi',
    name: L('Qirrali taxta 25×100×3000 mm, archa', 'Доска обрезная 25×100×3000 мм, ель'),
    description: L('Obreshyotka va yordamchi ishlar uchun yupqa taxta.', 'Тонкая доска для обрешётки и вспомогательных работ.'),
    materialType: 'wood',
    grade: 'II',
    unit: 'piece',
    price: 18500,
    priceTiers: [{ minQty: 100, price: 17500 }],
    minOrderQty: 10,
    dimensions: { lengthMm: 3000, widthMm: 100, thicknessMm: 25 },
    weightKg: 3.3,
    stock: { status: 'low_stock', quantity: 140 },
    images: img('boards-light')
  },
  {
    sku: 'WOD-PLY-18',
    category: 'lumber',
    brand: null,
    supplier: 'yogoch-ustasi',
    name: L('Fanera FK 18 mm, 1525×1525 mm, qayin', 'Фанера ФК 18 мм, 1525×1525 мм, берёза'),
    description: L(
      'Mebel, pol osti va qolip uchun qayin fanerasi. Karbamid yelim (E1).',
      'Берёзовая фанера для мебели, подложки пола и опалубки. Карбамидный клей (E1).'
    ),
    materialType: 'plywood',
    grade: '2/3',
    unit: 'sheet',
    price: 385000,
    priceTiers: [{ minQty: 20, price: 368000 }, { minQty: 50, price: 355000 }],
    dimensions: { lengthMm: 1525, widthMm: 1525, thicknessMm: 18 },
    weightKg: 17.5,
    unitsPerPallet: 50,
    specs: [spec('Yelim turi', 'Тип клея', 'Karbamid (E1)', 'Карбамидный (E1)'), spec('Qatlamlar', 'Слоёв', '13')],
    stock: { status: 'in_stock', quantity: 220 },
    images: img('plywood')
  },
  {
    sku: 'WOD-OSB3-9',
    category: 'lumber',
    brand: 'kronospan',
    supplier: 'yogoch-ustasi',
    name: L('OSB-3 plita 9 mm, 1250×2500 mm', 'Плита OSB-3 9 мм, 1250×2500 мм'),
    description: L(
      'Namga chidamli yoʻnaltirilgan qirindili plita: tom osti, devor va pol uchun.',
      'Влагостойкая ориентированно-стружечная плита для кровли, стен и пола.'
    ),
    materialType: 'osb',
    grade: 'OSB-3',
    unit: 'sheet',
    price: 158000,
    priceTiers: [{ minQty: 30, price: 151000 }, { minQty: 100, price: 146000 }],
    dimensions: { lengthMm: 2500, widthMm: 1250, thicknessMm: 9 },
    weightKg: 17.2,
    unitsPerPallet: 100,
    stock: { status: 'in_stock', quantity: 600 },
    images: img('osb'),
    isFeatured: true
  },
  {
    sku: 'WOD-OSB3-12',
    category: 'lumber',
    brand: 'kronospan',
    supplier: 'yogoch-ustasi',
    name: L('OSB-3 plita 12 mm, 1250×2500 mm', 'Плита OSB-3 12 мм, 1250×2500 мм'),
    description: L('Qalin OSB: pol va kuchaytirilgan asoslar uchun.', 'Утолщённая OSB для полов и усиленных оснований.'),
    materialType: 'osb',
    grade: 'OSB-3',
    unit: 'sheet',
    price: 199000,
    priceTiers: [{ minQty: 30, price: 191000 }],
    dimensions: { lengthMm: 2500, widthMm: 1250, thicknessMm: 12 },
    weightKg: 22.9,
    unitsPerPallet: 75,
    stock: { status: 'on_order', quantity: null },
    leadTimeDays: 5,
    images: img('osb')
  },

  /* ------------------------------------------------ drywall */
  {
    sku: 'GKL-KN-125',
    category: 'drywall',
    brand: 'knauf',
    supplier: 'gips-pro',
    name: L('Gipsokarton Knauf GKL 12,5 mm, 1200×2500 mm', 'Гипсокартон Knauf ГКЛ 12,5 мм, 1200×2500 мм'),
    description: L(
      'Quruq xonalarda devor qoplamasi va toʻsiqlar uchun standart gipsokarton list.',
      'Стандартный гипсокартонный лист для обшивки стен и перегородок в сухих помещениях.'
    ),
    materialType: 'gypsum',
    grade: 'GKL',
    unit: 'sheet',
    price: 79000,
    priceTiers: [{ minQty: 50, price: 76000 }, { minQty: 200, price: 73500 }],
    dimensions: { lengthMm: 2500, widthMm: 1200, thicknessMm: 12.5 },
    weightKg: 25,
    unitsPerPallet: 66,
    specs: [spec('Chekka turi', 'Тип кромки', 'PLUK'), spec('Yonuvchanlik', 'Горючесть', 'G1', 'Г1')],
    stock: { status: 'in_stock', quantity: 1800 },
    images: img('drywall'),
    isFeatured: true
  },
  {
    sku: 'GKL-KN-MR125',
    category: 'drywall',
    brand: 'knauf',
    supplier: 'gips-pro',
    name: L('Namga chidamli gipsokarton Knauf GKLV 12,5 mm', 'Гипсокартон влагостойкий Knauf ГКЛВ 12,5 мм'),
    description: L('Hammom, oshxona va yuqori namlikli xonalar uchun.', 'Для ванных, кухонь и помещений с повышенной влажностью.'),
    materialType: 'gypsum',
    grade: 'GKLV',
    unit: 'sheet',
    price: 96000,
    priceTiers: [{ minQty: 50, price: 92500 }],
    dimensions: { lengthMm: 2500, widthMm: 1200, thicknessMm: 12.5 },
    weightKg: 25.5,
    unitsPerPallet: 66,
    stock: { status: 'in_stock', quantity: 760 },
    images: img('drywall-green')
  },
  {
    sku: 'GKL-KN-95',
    category: 'drywall',
    brand: 'knauf',
    supplier: 'gips-pro',
    name: L('Shift gipsokartoni Knauf 9,5 mm, 1200×2500 mm', 'Гипсокартон потолочный Knauf 9,5 мм, 1200×2500 мм'),
    description: L('Yengil list: shiftlar va egri konstruksiyalar uchun.', 'Облегчённый лист для потолков и криволинейных конструкций.'),
    materialType: 'gypsum',
    grade: 'GKL',
    unit: 'sheet',
    price: 69000,
    priceTiers: [{ minQty: 50, price: 66500 }],
    dimensions: { lengthMm: 2500, widthMm: 1200, thicknessMm: 9.5 },
    weightKg: 20,
    unitsPerPallet: 80,
    stock: { status: 'low_stock', quantity: 90 },
    images: img('drywall')
  },
  {
    sku: 'GKL-PR-CD60',
    category: 'drywall',
    brand: 'knauf',
    supplier: 'gips-pro',
    name: L('Shift profili CD 60×27 mm, 3 m, 0,6 mm', 'Профиль потолочный CD 60×27 мм, 3 м, 0,6 мм'),
    description: L('Rux qoplangan poʻlat profil — gipsokarton karkasi uchun.', 'Оцинкованный стальной профиль для каркаса под гипсокартон.'),
    materialType: 'galvanized_steel',
    grade: 'DX51D',
    unit: 'piece',
    price: 24500,
    priceTiers: [{ minQty: 100, price: 23300 }, { minQty: 500, price: 22000 }],
    minOrderQty: 5,
    dimensions: { lengthMm: 3000, widthMm: 60, heightMm: 27, thicknessMm: 0.6 },
    weightKg: 1.6,
    stock: { status: 'in_stock', quantity: 4200 },
    images: img('profile')
  },
  {
    sku: 'GKL-PR-UD27',
    category: 'drywall',
    brand: 'knauf',
    supplier: 'gips-pro',
    name: L('Yoʻnaltiruvchi profil UD 27×28 mm, 3 m', 'Профиль направляющий UD 27×28 мм, 3 м'),
    description: L('CD profillar uchun perimetr profili.', 'Периметральный профиль для профилей CD.'),
    materialType: 'galvanized_steel',
    grade: 'DX51D',
    unit: 'piece',
    price: 17800,
    priceTiers: [{ minQty: 100, price: 16900 }],
    minOrderQty: 5,
    dimensions: { lengthMm: 3000, widthMm: 28, heightMm: 27, thicknessMm: 0.6 },
    weightKg: 1.1,
    stock: { status: 'in_stock', quantity: 2600 },
    images: img('profile')
  },

  /* ------------------------------------------------ pipes */
  {
    sku: 'PIP-PPR-20',
    category: 'pipes-fittings',
    brand: 'kalde',
    supplier: 'aqua-quvur',
    name: L('PPR quvur PN20, 20×3,4 mm, 4 m', 'Труба PPR PN20, 20×3,4 мм, 4 м'),
    description: L(
      'Sovuq va issiq suv taʼminoti uchun polipropilen quvur. Payvandlash orqali ulanadi.',
      'Полипропиленовая труба для холодного и горячего водоснабжения. Соединение пайкой.'
    ),
    materialType: 'ppr',
    grade: 'PN20',
    unit: 'm',
    price: 6800,
    priceTiers: [{ minQty: 100, price: 6300 }, { minQty: 400, price: 5900 }],
    minOrderQty: 4,
    orderStep: 4,
    dimensions: { lengthMm: 4000, diameterMm: 20, thicknessMm: 3.4 },
    weightKg: 0.17,
    specs: [
      spec('Maksimal harorat', 'Макс. температура', '95 °C'),
      spec('Ishchi bosim', 'Рабочее давление', '20 bar', '20 бар')
    ],
    stock: { status: 'in_stock', quantity: 3600 },
    images: img('pipe-ppr'),
    isFeatured: true
  },
  {
    sku: 'PIP-PPR-25',
    category: 'pipes-fittings',
    brand: 'kalde',
    supplier: 'aqua-quvur',
    name: L('PPR quvur PN20, 25×4,2 mm, 4 m', 'Труба PPR PN20, 25×4,2 мм, 4 м'),
    description: L('Suv taʼminoti magistrallari uchun PPR quvur.', 'Труба PPR для магистралей водоснабжения.'),
    materialType: 'ppr',
    grade: 'PN20',
    unit: 'm',
    price: 10400,
    priceTiers: [{ minQty: 100, price: 9700 }],
    minOrderQty: 4,
    orderStep: 4,
    dimensions: { lengthMm: 4000, diameterMm: 25, thicknessMm: 4.2 },
    weightKg: 0.27,
    stock: { status: 'in_stock', quantity: 2000 },
    images: img('pipe-ppr')
  },
  {
    sku: 'PIP-PPR-32AL',
    category: 'pipes-fittings',
    brand: 'kalde',
    supplier: 'aqua-quvur',
    name: L('Alyumin bilan armaturalangan PPR quvur PN25, 32 mm', 'Труба PPR армированная алюминием PN25, 32 мм'),
    description: L('Isitish tizimlari uchun: kam chiziqli kengayish.', 'Для систем отопления: низкое линейное расширение.'),
    materialType: 'ppr',
    grade: 'PN25',
    unit: 'm',
    price: 24000,
    minOrderQty: 4,
    orderStep: 4,
    dimensions: { lengthMm: 4000, diameterMm: 32, thicknessMm: 5.4 },
    weightKg: 0.52,
    stock: { status: 'on_order', quantity: null },
    leadTimeDays: 7,
    images: img('pipe-ppr-al')
  },
  {
    sku: 'PIP-PVC-110',
    category: 'pipes-fittings',
    brand: 'wavin',
    supplier: 'aqua-quvur',
    name: L('Kanalizatsiya quvuri PVX 110×2,2 mm, 3 m', 'Труба канализационная ПВХ 110×2,2 мм, 3 м'),
    description: L('Ichki kanalizatsiya uchun rozetkali quvur.', 'Раструбная труба для внутренней канализации.'),
    materialType: 'pvc',
    grade: 'SN2',
    unit: 'piece',
    price: 64000,
    priceTiers: [{ minQty: 20, price: 60500 }],
    dimensions: { lengthMm: 3000, diameterMm: 110, thicknessMm: 2.2 },
    weightKg: 3.4,
    stock: { status: 'in_stock', quantity: 260 },
    images: img('pipe-sewer')
  },
  {
    sku: 'PIP-PVC-50',
    category: 'pipes-fittings',
    brand: 'wavin',
    supplier: 'aqua-quvur',
    name: L('Kanalizatsiya quvuri PVX 50×1,8 mm, 2 m', 'Труба канализационная ПВХ 50×1,8 мм, 2 м'),
    description: L('Rakovina va dush chiqishlari uchun.', 'Для отводов от раковин и душевых.'),
    materialType: 'pvc',
    grade: 'SN2',
    unit: 'piece',
    price: 21500,
    priceTiers: [{ minQty: 20, price: 19900 }],
    dimensions: { lengthMm: 2000, diameterMm: 50, thicknessMm: 1.8 },
    weightKg: 0.9,
    stock: { status: 'in_stock', quantity: 410 },
    images: img('pipe-sewer')
  },
  {
    sku: 'PIP-FIT-20EL',
    category: 'pipes-fittings',
    brand: 'kalde',
    supplier: 'aqua-quvur',
    name: L('PPR burchak 90°, 20 mm (10 dona)', 'Угольник PPR 90°, 20 мм (10 шт.)'),
    description: L('Quvurni 90° ga burish uchun payvandlanadigan fiting.', 'Паечный фитинг для поворота трубы на 90°.'),
    materialType: 'ppr',
    grade: 'PN25',
    unit: 'pack',
    price: 9000,
    priceTiers: [{ minQty: 20, price: 8300 }],
    dimensions: { diameterMm: 20 },
    weightKg: 0.12,
    stock: { status: 'in_stock', quantity: 900 },
    images: img('fitting-elbow')
  },

  /* ------------------------------------------------ fasteners */
  {
    sku: 'FST-SCR-TN25',
    category: 'fasteners',
    brand: 'knauf',
    supplier: 'krepyoj-market',
    name: L('Gipsokarton uchun shuruplar TN 3,5×25 mm (1000 dona)', 'Саморезы для гипсокартона TN 3,5×25 мм (1000 шт.)'),
    description: L('Gipsokartonni metall profilga mahkamlash uchun fosfatlangan shuruplar.', 'Фосфатированные саморезы для крепления ГКЛ к металлическому профилю.'),
    materialType: 'steel',
    grade: '',
    unit: 'box',
    price: 62000,
    priceTiers: [{ minQty: 10, price: 58500 }],
    dimensions: { lengthMm: 25, diameterMm: 3.5 },
    weightKg: 1.9,
    stock: { status: 'in_stock', quantity: 340 },
    images: img('screws-box')
  },
  {
    sku: 'FST-ANC-10100',
    category: 'fasteners',
    brand: 'fischer',
    supplier: 'krepyoj-market',
    name: L('Ankerli bolt 10×100 mm, gaykali (50 dona)', 'Анкерный болт с гайкой 10×100 мм (50 шт.)'),
    description: L(
      'Beton va gʻishtga ogʻir konstruksiyalarni mahkamlash uchun rux qoplangan anker.',
      'Оцинкованный анкер для крепления тяжёлых конструкций к бетону и кирпичу.'
    ),
    materialType: 'galvanized_steel',
    grade: '5.8',
    unit: 'box',
    price: 118000,
    priceTiers: [{ minQty: 10, price: 110000 }],
    dimensions: { lengthMm: 100, diameterMm: 10 },
    weightKg: 2.6,
    specs: [spec('Tavsiya etilgan yuk (beton)', 'Рекомендуемая нагрузка (бетон)', '2,4 kN', '2,4 кН')],
    stock: { status: 'in_stock', quantity: 120 },
    images: img('anchor'),
    isFeatured: true
  },
  {
    sku: 'FST-DWL-640',
    category: 'fasteners',
    brand: 'fischer',
    supplier: 'krepyoj-market',
    name: L('Neylon dyubel 6×40 mm (100 dona)', 'Дюбель нейлоновый 6×40 мм (100 шт.)'),
    description: L('Universal dyubel: beton, gʻisht va gazobeton uchun.', 'Универсальный дюбель для бетона, кирпича и газобетона.'),
    materialType: 'other',
    grade: '',
    unit: 'pack',
    price: 32000,
    priceTiers: [{ minQty: 20, price: 29500 }],
    dimensions: { lengthMm: 40, diameterMm: 6 },
    weightKg: 0.1,
    stock: { status: 'in_stock', quantity: 600 },
    images: img('dowels')
  },
  {
    sku: 'FST-SCR-WD75',
    category: 'fasteners',
    brand: null,
    supplier: 'krepyoj-market',
    name: L('Yogʻoch uchun shuruplar 4,2×75 mm, sariq rux (500 dona)', 'Саморезы по дереву 4,2×75 мм, жёлтый цинк (500 шт.)'),
    description: L('Yogʻoch konstruksiyalarni yigʻish uchun oʻtkir uchli shuruplar.', 'Саморезы с острым наконечником для сборки деревянных конструкций.'),
    materialType: 'steel',
    grade: '',
    unit: 'box',
    price: 54000,
    dimensions: { lengthMm: 75, diameterMm: 4.2 },
    weightKg: 3.1,
    stock: { status: 'low_stock', quantity: 18 },
    images: img('screws-box-gold')
  },
  {
    sku: 'FST-BLT-M1280',
    category: 'fasteners',
    brand: null,
    supplier: 'krepyoj-market',
    name: L('Olti qirrali bolt M12×80, 8.8, DIN 933 (25 dona)', 'Болт шестигранный M12×80, 8.8, DIN 933 (25 шт.)'),
    description: L('Metall konstruksiyalar uchun yuqori mustahkamlikdagi bolt.', 'Высокопрочный болт для металлоконструкций.'),
    materialType: 'steel',
    grade: '8.8',
    unit: 'pack',
    price: 47000,
    dimensions: { lengthMm: 80, diameterMm: 12 },
    weightKg: 2.4,
    stock: { status: 'in_stock', quantity: 75 },
    images: img('bolt')
  },
  {
    sku: 'FST-NAIL-4100',
    category: 'fasteners',
    brand: null,
    supplier: 'krepyoj-market',
    name: L('Qurilish mixi 4×100 mm', 'Гвозди строительные 4×100 мм'),
    description: L('Kilogramm hisobida sotiladigan umumiy qurilish mixlari.', 'Строительные гвозди общего назначения на развес.'),
    materialType: 'steel',
    grade: '',
    unit: 'kg',
    price: 19500,
    priceTiers: [{ minQty: 25, price: 18000 }],
    minOrderQty: 1,
    orderStep: 0.5,
    dimensions: { lengthMm: 100, diameterMm: 4 },
    stock: { status: 'in_stock', quantity: 800 },
    images: img('nails')
  },

  /* ------------------------------------------------ rebar & metal */
  {
    sku: 'MET-RB-A500-12',
    category: 'rebar-metal',
    brand: null,
    supplier: 'metall-invest',
    name: L('Armatura A500C, Ø12 mm, 11,7 m', 'Арматура A500C, Ø12 мм, 11,7 м'),
    description: L(
      'Poydevor va monolit konstruksiyalar uchun payvandlanadigan davriy profilli armatura.',
      'Свариваемая арматура периодического профиля для фундаментов и монолитных конструкций.'
    ),
    materialType: 'steel',
    grade: 'A500C',
    unit: 'ton',
    price: 9650000,
    priceTiers: [{ minQty: 5, price: 9350000 }, { minQty: 20, price: 9100000 }],
    minOrderQty: 0.5,
    orderStep: 0.1,
    dimensions: { lengthMm: 11700, diameterMm: 12 },
    specs: [
      spec('1 metr ogʻirligi', 'Вес 1 м', '0,888 kg', '0,888 кг'),
      spec('1 tonnada', 'В 1 тонне', '≈ 1126 m', '≈ 1126 м'),
      spec('Standart', 'Стандарт', 'GOST 34028-2016')
    ],
    stock: { status: 'in_stock', quantity: 86 },
    images: img('rebar'),
    isFeatured: true
  },
  {
    sku: 'MET-RB-A500-10',
    category: 'rebar-metal',
    brand: null,
    supplier: 'metall-invest',
    name: L('Armatura A500C, Ø10 mm, 11,7 m', 'Арматура A500C, Ø10 мм, 11,7 м'),
    description: L('Plitalar va devorlar uchun armatura.', 'Арматура для армирования плит и стен.'),
    materialType: 'steel',
    grade: 'A500C',
    unit: 'ton',
    price: 9700000,
    priceTiers: [{ minQty: 5, price: 9400000 }, { minQty: 20, price: 9150000 }],
    minOrderQty: 0.5,
    orderStep: 0.1,
    dimensions: { lengthMm: 11700, diameterMm: 10 },
    specs: [spec('1 metr ogʻirligi', 'Вес 1 м', '0,617 kg', '0,617 кг')],
    stock: { status: 'in_stock', quantity: 54 },
    images: img('rebar')
  },
  {
    sku: 'MET-RB-A500-8M',
    category: 'rebar-metal',
    brand: null,
    supplier: 'metall-invest',
    name: L('Armatura A500C, Ø8 mm, uzunlik metri', 'Арматура A500C, Ø8 мм, погонный метр'),
    description: L('Kichik hajmlar uchun metrlab kesib beriladi.', 'Нарезка по метрам для небольших объёмов.'),
    materialType: 'steel',
    grade: 'A500C',
    unit: 'm',
    price: 4300,
    priceTiers: [{ minQty: 500, price: 4050 }],
    minOrderQty: 10,
    dimensions: { diameterMm: 8 },
    weightKg: 0.395,
    stock: { status: 'in_stock', quantity: null },
    images: img('rebar')
  },
  {
    sku: 'MET-MESH-5050',
    category: 'rebar-metal',
    brand: null,
    supplier: 'metall-invest',
    name: L('Tosh devor toʻri 50×50 mm, Ø4 mm, 0,5×2 m', 'Сетка кладочная 50×50 мм, Ø4 мм, 0,5×2 м'),
    description: L('Gʻisht va blok terishni armaturalash uchun payvandlangan toʻr.', 'Сварная сетка для армирования кладки из кирпича и блоков.'),
    materialType: 'steel',
    grade: 'Vr-1',
    unit: 'sheet',
    price: 38000,
    priceTiers: [{ minQty: 50, price: 35500 }],
    dimensions: { lengthMm: 2000, widthMm: 500, diameterMm: 4 },
    weightKg: 1.9,
    stock: { status: 'in_stock', quantity: 700 },
    images: img('mesh')
  },
  {
    sku: 'MET-PP-40202',
    category: 'rebar-metal',
    brand: null,
    supplier: 'metall-invest',
    name: L('Profil quvur 40×20×2 mm, 6 m', 'Труба профильная 40×20×2 мм, 6 м'),
    description: L('Karkaslar, darvozalar va shiyponlar uchun toʻrtburchak quvur.', 'Прямоугольная труба для каркасов, ворот и навесов.'),
    materialType: 'steel',
    grade: 'St3',
    unit: 'm',
    price: 26500,
    priceTiers: [{ minQty: 120, price: 25200 }],
    minOrderQty: 6,
    orderStep: 6,
    dimensions: { lengthMm: 6000, widthMm: 40, heightMm: 20, thicknessMm: 2 },
    weightKg: 1.72,
    stock: { status: 'low_stock', quantity: 240 },
    images: img('profile-pipe')
  },

  /* ------------------------------------------------ power tools */
  {
    sku: 'TLS-BSH-GBH226',
    category: 'power-tools',
    brand: 'bosch',
    supplier: 'asbob-pro',
    name: L('Perforator Bosch Professional GBH 2-26, 800 Vt', 'Перфоратор Bosch Professional GBH 2-26, 800 Вт'),
    description: L(
      'Beton va gʻishtni burgʻilash va yengil oʻyish uchun SDS-plus perforator. Rasmiy kafolat.',
      'Перфоратор SDS-plus для сверления и лёгкого долбления бетона и кирпича. Официальная гарантия.'
    ),
    materialType: 'other',
    grade: '',
    unit: 'piece',
    price: 2690000,
    oldPrice: 2890000,
    weightKg: 2.7,
    specs: [
      spec('Quvvat', 'Мощность', '800 Vt', '800 Вт'),
      spec('Zarb kuchi', 'Энергия удара', '2,7 J', '2,7 Дж'),
      spec('Patron', 'Патрон', 'SDS-plus'),
      spec('Betonda teshik', 'Сверление бетона', '26 mm gacha', 'до 26 мм'),
      spec('Kafolat', 'Гарантия', '12 oy', '12 месяцев')
    ],
    stock: { status: 'in_stock', quantity: 14 },
    images: img('rotary-hammer'),
    isFeatured: true
  },
  {
    sku: 'TLS-MKT-GA5030',
    category: 'power-tools',
    brand: 'makita',
    supplier: 'asbob-pro',
    name: L('Burchak silliqlash mashinasi Makita GA5030, 125 mm, 720 Vt', 'Угловая шлифмашина Makita GA5030, 125 мм, 720 Вт'),
    description: L('Metall va toshni kesish hamda silliqlash uchun ixcham mashina.', 'Компактная УШМ для резки и шлифовки металла и камня.'),
    materialType: 'other',
    grade: '',
    unit: 'piece',
    price: 985000,
    priceTiers: [{ minQty: 5, price: 945000 }],
    dimensions: { diameterMm: 125 },
    weightKg: 1.4,
    specs: [spec('Quvvat', 'Мощность', '720 Vt', '720 Вт'), spec('Aylanish tezligi', 'Частота вращения', '11 000 ayl/daq', '11 000 об/мин')],
    stock: { status: 'in_stock', quantity: 22 },
    images: img('grinder')
  },
  {
    sku: 'TLS-DW-DCD771',
    category: 'power-tools',
    brand: 'dewalt',
    supplier: 'asbob-pro',
    name: L('Akkumulyatorli drel-shurupovyort DeWalt DCD771, 18 V', 'Аккумуляторная дрель-шуруповёрт DeWalt DCD771, 18 В'),
    description: L('Ikki akkumulyator va zaryadlovchi bilan toʻplam, keysda.', 'Комплект с двумя аккумуляторами и зарядным устройством, в кейсе.'),
    materialType: 'other',
    grade: '',
    unit: 'set',
    price: 2350000,
    weightKg: 1.7,
    specs: [spec('Kuchlanish', 'Напряжение', '18 V', '18 В'), spec('Burovchi moment', 'Крутящий момент', '42 N·m', '42 Н·м')],
    stock: { status: 'low_stock', quantity: 3 },
    images: img('drill')
  },
  {
    sku: 'TLS-BSH-GWS750',
    category: 'power-tools',
    brand: 'bosch',
    supplier: 'asbob-pro',
    name: L('Burchak silliqlash mashinasi Bosch GWS 750, 125 mm', 'Угловая шлифмашина Bosch GWS 750, 125 мм'),
    description: L('Kundalik qurilish ishlari uchun ishonchli UShM.', 'Надёжная УШМ для ежедневных строительных работ.'),
    materialType: 'other',
    grade: '',
    unit: 'piece',
    price: 1050000,
    dimensions: { diameterMm: 125 },
    weightKg: 1.9,
    stock: { status: 'out_of_stock', quantity: 0 },
    leadTimeDays: 14,
    images: img('grinder')
  },
  {
    sku: 'TLS-MKT-HR2470',
    category: 'power-tools',
    brand: 'makita',
    supplier: 'asbob-pro',
    name: L('Perforator Makita HR2470, 780 Vt', 'Перфоратор Makita HR2470, 780 Вт'),
    description: L('Uch rejimli klassik perforator.', 'Классический трёхрежимный перфоратор.'),
    materialType: 'other',
    grade: '',
    unit: 'piece',
    price: 2450000,
    weightKg: 2.9,
    stock: { status: 'on_order', quantity: null },
    leadTimeDays: 10,
    images: img('rotary-hammer')
  },

  /* ------------------------------------------------ roofing & insulation */
  {
    sku: 'ROF-C8-045',
    category: 'roofing-insulation',
    brand: 'grand-line',
    supplier: 'tom-master',
    name: L('Profnastil S8, 0,45 mm, rux qoplamali', 'Профнастил С8, 0,45 мм, оцинкованный'),
    description: L(
      'Devor qoplamasi, toʻsiqlar va yengil tomlar uchun trapetsiya profilli list. Istalgan uzunlikda kesiladi.',
      'Трапециевидный лист для облицовки стен, заборов и лёгких кровель. Резка в любой размер.'
    ),
    materialType: 'galvanized_steel',
    grade: 'C8',
    unit: 'm2',
    price: 76000,
    priceTiers: [{ minQty: 100, price: 72000 }, { minQty: 500, price: 68500 }],
    minOrderQty: 10,
    dimensions: { widthMm: 1200, thicknessMm: 0.45 },
    weightKg: 4.2,
    stock: { status: 'in_stock', quantity: 3200 },
    leadTimeDays: 1,
    images: img('roof-sheet'),
    isFeatured: true
  },
  {
    sku: 'ROF-RW-LB50',
    category: 'roofing-insulation',
    brand: 'rockwool',
    supplier: 'tom-master',
    name: L('Mineral paxta Rockwool Light Butts 50 mm (5,76 m²)', 'Минеральная вата Rockwool Лайт Баттс 50 мм (5,76 м²)'),
    description: L(
      'Karkas devorlar, mansardlar va yopmalar uchun yengil issiqlik izolyatsiyasi plitalari.',
      'Лёгкие теплоизоляционные плиты для каркасных стен, мансард и перекрытий.'
    ),
    materialType: 'mineral_wool',
    grade: '37 kg/m³',
    unit: 'pack',
    price: 189000,
    priceTiers: [{ minQty: 20, price: 179000 }],
    dimensions: { lengthMm: 1000, widthMm: 600, thicknessMm: 50 },
    weightKg: 10.7,
    specs: [
      spec('Qadoqdagi maydon', 'Площадь в упаковке', '5,76 m²', '5,76 м²'),
      spec('Issiqlik oʻtkazuvchanlik', 'Теплопроводность', '0,036 Vt/(m·K)', '0,036 Вт/(м·К)'),
      spec('Yonuvchanlik', 'Горючесть', 'NG (yonmaydi)', 'НГ (негорючий)')
    ],
    stock: { status: 'in_stock', quantity: 160 },
    images: img('mineral-wool')
  },
  {
    sku: 'ROF-XPS-CE50',
    category: 'roofing-insulation',
    brand: 'technonicol',
    supplier: 'tom-master',
    name: L('Ekstruziyalangan penopolistirol Carbon Eco 50 mm', 'Экструзионный пенополистирол Carbon Eco 50 мм'),
    description: L('Poydevor, pol va tekis tomlarni isitish uchun XPS plitalar (8 dona).', 'Плиты XPS для утепления фундамента, пола и плоской кровли (8 шт.).'),
    materialType: 'polystyrene',
    grade: 'XPS 30-250',
    unit: 'pack',
    price: 410000,
    dimensions: { lengthMm: 1180, widthMm: 580, thicknessMm: 50 },
    weightKg: 8.2,
    specs: [spec('Qadoqdagi hajm', 'Объём упаковки', '0,274 m³', '0,274 м³')],
    stock: { status: 'in_stock', quantity: 95 },
    images: img('xps')
  },
  {
    sku: 'ROF-BIT-EPP',
    category: 'roofing-insulation',
    brand: 'technonicol',
    supplier: 'tom-master',
    name: L('Bitumli gidroizolyatsiya Technoelast EPP, 10 m²', 'Гидроизоляция битумная Техноэласт ЭПП, 10 м²'),
    description: L('Poydevor va tomlar uchun eritib yopishtiriladigan material.', 'Наплавляемый материал для фундаментов и кровли.'),
    materialType: 'bitumen',
    grade: 'EPP',
    unit: 'roll',
    price: 365000,
    priceTiers: [{ minQty: 20, price: 349000 }],
    dimensions: { widthMm: 1000, thicknessMm: 4 },
    weightKg: 49,
    stock: { status: 'low_stock', quantity: 12 },
    images: img('bitumen-roll')
  },

  /* ------------------------------------------------ paints */
  {
    sku: 'PNT-TK-HRM9',
    category: 'paints-finishes',
    brand: 'tikkurila',
    supplier: 'rang-uy',
    name: L('Ichki boʻyoq Tikkurila Harmony, oq, 9 l', 'Интерьерная краска Tikkurila Harmony, белая, 9 л'),
    description: L(
      'Devor va shiftlar uchun chuqur mat akril boʻyoq. Istalgan rangga boʻyab beriladi.',
      'Глубокоматовая акриловая краска для стен и потолков. Колеровка в любой цвет.'
    ),
    materialType: 'acrylic',
    grade: '',
    unit: 'piece',
    price: 820000,
    priceTiers: [{ minQty: 10, price: 790000 }],
    weightKg: 13.5,
    specs: [spec('Sarfi', 'Расход', '8–10 m²/l', '8–10 м²/л'), spec('Yaltiroqlik', 'Степень блеска', 'Chuqur mat', 'Глубокоматовая')],
    stock: { status: 'in_stock', quantity: 44 },
    images: img('paint-bucket')
  },
  {
    sku: 'PNT-CR-CT17',
    category: 'paints-finishes',
    brand: 'ceresit',
    supplier: 'rang-uy',
    name: L('Chuqur kiruvchi gruntovka Ceresit CT 17, 10 l', 'Грунтовка глубокого проникновения Ceresit CT 17, 10 л'),
    description: L('Gʻovak asoslarni mustahkamlaydi va boʻyoq sarfini kamaytiradi.', 'Укрепляет пористые основания и снижает расход краски.'),
    materialType: 'acrylic',
    grade: '',
    unit: 'piece',
    price: 265000,
    priceTiers: [{ minQty: 10, price: 251000 }],
    weightKg: 10,
    specs: [spec('Sarfi', 'Расход', '0,1–0,2 l/m²', '0,1–0,2 л/м²')],
    stock: { status: 'in_stock', quantity: 70 },
    images: img('primer-canister')
  }
];

module.exports = { categories, brands, suppliers, products };
